name: Automerge
on:
  pull_request_target:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          github-token: ${{ secrets.PAT }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "github-actions[bot]"
          merge-method: REBASE

      # - name: automerge
      #   uses: "pascalgn/automerge-action@v0.14.3"
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     # retry every 3 sec for 10 minutes
      #     MERGE_RETRIES: 200
      #     MERGE_RETRY_SLEEP: 3000
      #     MERGE_COMMIT_MESSAGE: pull-request-title
      #     MERGE_METHOD: rebase
      #     UPDATE_METHOD: rebase
      #     UPDATE_RETRIES: 6

