CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	owner TEXT NOT NULL,
	created TIMESTAMP NOT NULL,
	body TEXT NOT NULL,
	votes INTEGER NOT NULL,
	FOREIGN KEY (user_id, owner) REFERENCES users (id, name)
		ON DELETE CASCADE
);